// <auto-generated />
namespace AutofacDatatable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aman21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aman21));
        
        string IMigrationMetadata.Id
        {
            get { return "201708121002583_aman21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
